### ISSUE TITLE
Typo in Readme. [pyvis.py] should be [pyviz.py].

### ISSUE THREAD

**Issue by davhojt** [Metazeta/push_swap_visualizer#1]
Hey.
Your readme has a typo in that the file name to launch has an 's' instead of a 'z'.

The visualizer is great. Really helps to see what crazy things my push_swap was up to. Appreciate it.

Dav.

**Comment by Metazeta** [comment]
Indeed, thanks !
I don't know how you can finish push_swap without a visualizer of some kind.
Have fun.
